services:
  web:
    build:
      context: .
      args:
        - DEV=true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      args:
        - DEV=true
    command: celery -A app worker --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

  celery-beat:
    build:
      context: .
      args:
        - DEV=true
    command: celery -A app beat --loglevel=info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - db

volumes:
  postgres_data:
