---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker compose run --rm web python manage.py test
      - name: flake8
        run:  docker compose run --rm web flake8 .
      - name: isort
        run: docker compose run --rm web isort .
      - name: mypy
        run: docker compose run --rm web mypy .