---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create dummy .env file for tests
        run: |
          echo "DEBUG=True" > .env
          echo "SECRET_KEY=testkey" >> .env
          echo "DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1" >> .env
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> .env
          echo "REDIS_URL=redis://redis:6379" >> .env
          echo "EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend" >> .env
          echo "DEFAULT_FROM_EMAIL=restaurant@example.com" >> .env
      - name: Rebuild image
        run: docker compose build --no-cache
      - name: Test
        run: docker compose run --rm web python manage.py test
      - name: flake8
        run:  docker compose run --rm web flake8 .
      - name: isort
        run: docker compose run --rm web isort .
      - name: mypy
        run: docker compose run --rm web mypy .